using Microsoft.Glee.Drawing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GraphDraw
{
    public static class ColorParseStuff
    {
        public static Color FromName(string colorName)
        {
            switch (colorName)
            {
                case "mediumslateblue": return Color.MediumSlateBlue;
                case "mediumspringgreen": return Color.MediumSpringGreen;
                case "mediumturquoise": return Color.MediumTurquoise;
                case "mediumvioletred": return Color.MediumVioletRed;
                case "midnightblue": return Color.MidnightBlue;
                case "mintcream": return Color.MintCream;
                case "mistyrose": return Color.MistyRose;
                case "moccasin": return Color.Moccasin;
                case "navajowhite": return Color.NavajoWhite;
                case "navy": return Color.Navy;
                case "oldlace": return Color.OldLace;
                case "olive": return Color.Olive;
                case "olivedrab": return Color.OliveDrab;
                case "orange": return Color.Orange;
                case "orangered": return Color.OrangeRed;
                case "mediumseagreen": return Color.MediumSeaGreen;
                case "mediumpurple": return Color.MediumPurple;
                case "mediumorchid": return Color.MediumOrchid;
                case "mediumblue": return Color.MediumBlue;
                case "lightgray": return Color.LightGray;
                case "lightgreen": return Color.LightGreen;
                case "lightpink": return Color.LightPink;
                case "lightsalmon": return Color.LightSalmon;
                case "lightseagreen": return Color.LightSeaGreen;
                case "lightskyblue": return Color.LightSkyBlue;
                case "lightslategray": return Color.LightSlateGray;
                case "lightsteelblue": return Color.LightSteelBlue;
                case "lightyellow": return Color.LightYellow;
                case "lime": return Color.Lime;
                case "limegreen": return Color.LimeGreen;
                case "linen": return Color.Linen;
                case "magenta": return Color.Magenta;
                case "maroon": return Color.Maroon;
                case "mediumaquamarine": return Color.MediumAquamarine;
                case "orchid": return Color.Orchid;
                case "palegoldenrod": return Color.PaleGoldenrod;
                case "palegreen": return Color.PaleGreen;
                case "paleturquoise": return Color.PaleTurquoise;
                case "slateblue": return Color.SlateBlue;
                case "slategray": return Color.SlateGray;
                case "snow": return Color.Snow;
                case "springgreen": return Color.SpringGreen;
                case "steelblue": return Color.SteelBlue;
                case "tan": return Color.Tan;
                case "teal": return Color.Teal;
                case "thistle": return Color.Thistle;
                case "tomato": return Color.Tomato;
                case "transparent": return Color.Transparent;
                case "turquoise": return Color.Turquoise;
                case "violet": return Color.Violet;
                case "wheat": return Color.Wheat;
                case "white": return Color.White;
                case "whitesmoke": return Color.WhiteSmoke;
                case "skyblue": return Color.SkyBlue;
                case "lightgoldenrodyellow": return Color.LightGoldenrodYellow;
                case "silver": return Color.Silver;
                case "seashell": return Color.SeaShell;
                case "palevioletred": return Color.PaleVioletRed;
                case "papayawhip": return Color.PapayaWhip;
                case "peachpuff": return Color.PeachPuff;
                case "peru": return Color.Peru;
                case "pink": return Color.Pink;
                case "plum": return Color.Plum;
                case "powderblue": return Color.PowderBlue;
                case "purple": return Color.Purple;
                case "red": return Color.Red;
                case "rosybrown": return Color.RosyBrown;
                case "royalblue": return Color.RoyalBlue;
                case "saddlebrown": return Color.SaddleBrown;
                case "salmon": return Color.Salmon;
                case "sandybrown": return Color.SandyBrown;
                case "seagreen": return Color.SeaGreen;
                case "sienna": return Color.Sienna;
                case "lightcyan": return Color.LightCyan;
                case "lightcoral": return Color.LightCoral;
                case "lightblue": return Color.LightBlue;
                case "darkolivegreen": return Color.DarkOliveGreen;
                case "darkmagenta": return Color.DarkMagenta;
                case "yellow": return Color.Yellow;
                case "darkgreen": return Color.DarkGreen;
                case "darkgray": return Color.DarkGray;
                case "darkgoldenrod": return Color.DarkGoldenrod;
                case "darkcyan": return Color.DarkCyan;
                case "darkblue": return Color.DarkBlue;
                case "cyan": return Color.Cyan;
                case "crimson": return Color.Crimson;
                case "cornsilk": return Color.Cornsilk;
                case "cornflowerblue": return Color.CornflowerBlue;
                case "coral": return Color.Coral;
                case "chocolate": return Color.Chocolate;
                case "chartreuse": return Color.Chartreuse;
                case "cadetblue": return Color.CadetBlue;
                case "burlywood": return Color.BurlyWood;
                case "brown": return Color.Brown;
                case "blueviolet": return Color.BlueViolet;
                case "blue": return Color.Blue;
                case "blanchedalmond": return Color.BlanchedAlmond;
                case "black": return Color.Black;
                case "bisque": return Color.Bisque;
                case "beige": return Color.Beige;
                case "azure": return Color.Azure;
                case "aquamarine": return Color.Aquamarine;
                case "aqua": return Color.Aqua;
                case "antiquewhite": return Color.AntiqueWhite;
                case "aliceblue": return Color.AliceBlue;
                case "darkorange": return Color.DarkOrange;
                case "darkorchid": return Color.DarkOrchid;
                case "darkkhaki": return Color.DarkKhaki;
                case "darksalmon": return Color.DarkSalmon;
                case "lemonchiffon": return Color.LemonChiffon;
                case "lawngreen": return Color.LawnGreen;
                case "lavenderblush": return Color.LavenderBlush;
                case "lavender": return Color.Lavender;
                case "khaki": return Color.Khaki;
                case "ivory": return Color.Ivory;
                case "indigo": return Color.Indigo;
                case "indianred": return Color.IndianRed;
                case "hotpink": return Color.HotPink;
                case "honeydew": return Color.Honeydew;
                case "darkred": return Color.DarkRed;
                case "green": return Color.Green;
                case "gray": return Color.Gray;
                case "goldenrod": return Color.Goldenrod;
                case "gold": return Color.Gold;
                case "greenyellow": return Color.GreenYellow;
                case "gainsboro": return Color.Gainsboro;
                case "darkseagreen": return Color.DarkSeaGreen;
                case "ghostwhite": return Color.GhostWhite;
                case "darkslategray": return Color.DarkSlateGray;
                case "darkturquoise": return Color.DarkTurquoise;
                case "darkviolet": return Color.DarkViolet;
                case "deeppink": return Color.DeepPink;
                case "darkslateblue": return Color.DarkSlateBlue;
                case "dimgray": return Color.DimGray;
                case "deepskyblue": return Color.DeepSkyBlue;
                case "fuchsia": return Color.Fuchsia;
                case "forestgreen": return Color.ForestGreen;
                case "yellowgreen": return Color.YellowGreen;
                case "firebrick": return Color.Firebrick;
                case "dodgerblue": return Color.DodgerBlue;
                case "floralwhite": return Color.FloralWhite;
                default:
                    return Color.White;
            }
        }
    }
}
